{
 "title": "Ecommerce Observability",
 "tags": [
  "ecommerce",
  "observability"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests Realtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ecommerce_http_requests_total[1m]))",
     "legendFormat": "requests/sec"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(ecommerce_http_request_errors_total[5m])) / clamp_min(sum(rate(ecommerce_http_requests_total[5m])), 1)",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "Top 5 Slowest Endpoints",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, sum by (route) (rate(ecommerce_http_request_duration_ms_sum[5m])) / clamp_min(sum by (route) (rate(ecommerce_http_request_duration_ms_count[5m])), 1))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Top 5 Error Types",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, sum by (route, status_code) (increase(ecommerce_http_request_errors_total[1h])))",
     "legendFormat": "{{status_code}} {{route}}"
    }
   ]
  },
  {
   "title": "Slow Application Methods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (class_name, method_name) (increase(ecommerce_slow_methods_total[1h]))",
     "legendFormat": "{{class_name}}.{{method_name}}"
    }
   ]
  }
 ]
}