<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\About\NewFolder\**" />
    <EmbeddedResource Remove="Features\About\NewFolder\**" />
    <None Remove="Features\About\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.1.3" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
    <PackageReference Include="HtmlSanitizer" Version="9.0.892" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ecommerce.Domain\Ecommerce.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\About\Dto\" />
    <Folder Include="Features\Account\Dto\" />
    <Folder Include="Features\Account\Queries\" />
    <Folder Include="Features\Dashboard\Commands\" />
    <Folder Include="Features\Reviews\Commands\DeleteReview\" />
    <Folder Include="Features\Reviews\Commands\UpdateReview\" />
  </ItemGroup>

</Project>

